title: "Flipwise Reno"
email: "info@flipwisereno.com"
description: "Reliable renovation solutions."
baseurl: "" 
url: "https://flipwisereno.com"

# remote_theme: "mmistakes/minimal-mistakes"
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown
permalink: /:title/

# Navigation menu
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Services"
    url: /services/
  - title: "Team"
    url: /team/
  - title: "Contact"
    url: /contact/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"

author:
  name: Flipwise Reno
  email: info@flipwisereno.com

# Force include all theme layout files
include:
  - _layouts
  - _includes
  - _sass
  - assets

